### ISSUE TITLE
remembered password is sometimes cleared when two tabs with Archipel are opened

### ISSUE THREAD

**Issue by Nowaker** [ArchipelProject/Archipel#1005]
I opened a second tab with Archipel by mistake. I got logged out of the first window, which is natural, but the remembered password was gone - I got empty fields. I am not able to reproduce the problem, probably there's some timing involved here, but I remember this problem happening to me from time to time since I started using Archipel.

**Comment by CyrilPeponnet** [comment]
As the UI is using a local cache this could be messed up with several instances.
