### ISSUE TITLE
Misleading error message after a failed migration (migration_uri unset)

### ISSUE THREAD

**Issue by smlautomat** [ArchipelProject/Archipel#1022]
Because of unset migration_uri variable in archipel.conf I was unable to migrate any VM to this host (and this is expected). Unfortunately, the error message does not help in finding the cause because it sounds: "Cannot read CA certificate  '/etc/pki/CA/cacert.pem': No such file or directory". After changing migration_uri to proper value, migration works like a charm.

Maybe the error message should look as something like "Cannot connect to $hypervisor. Please check migration_uri variable in archipel's configuration file."?

**Comment by CyrilPeponnet** [comment]
This is a libvirt message I can't change it.
