### ISSUE TITLE
Add the ability to add sound cards

### ISSUE THREAD

**Issue by BrunIF** [ArchipelProject/Archipel#1083]
Archipel can't work with sound cards. When I add via virsh or in the configuration window (Manual XML Editor), then everything works. But if I click on "Validate", then all changes disappear.
Make an extra tab for sound cards.

Example:

```
<sound model='es1370' />
```

**Comment by finasfinas** [comment]
I would also love to be able to add a soundcard to a VM, just like I add a serial device, a lan device or a block device. it's just another piece of hardware and in my particular case, I actually need it for all my mv's :)

**Comment by HTPC-Schrauber** [comment]
Soundcard can now be added via virsh
See https://github.com/ArchipelProject/Archipel/pull/1196

The changes from virsh are not longer lost when doing changes via ArchipelClient.
