### ISSUE TITLE
Support for fi keymap

### ISSUE THREAD

**Issue by tssge** [ArchipelProject/Archipel#1097]
Hello, 

Could you add keymap support for "fi"? Don't want to start scanning the CLA and writing it just for 2 lines.

It can be done the same as this commit, but just use "fi".
https://github.com/ArchipelProject/Archipel/commit/e26e3789d5739e35114dfe3689891404849e5cdb

Here's another issue but for another language:
https://github.com/ArchipelProject/Archipel/issues/498

Thank you.

**Comment by gurragurra** [comment]
Hi,
It would be really great if you, while you're at it, add a keymap for "sv" as well :-)
