### ISSUE TITLE
Can't see disks in client

### ISSUE THREAD

**Issue by daniellog** [ArchipelProject/Archipel#1100]
I've installed Archipel agent and the client running with nginx. I can create vm's fine but when I create a disk its not showing up on the list in the client. When I look in /vm/drives I can see the agent has created it...

root@viper:/vm/drives/77a9ac3e-73d1-11e4-84fb-90e2ba0cb951# ls -al
total 412
drwxrwxrwx 2 root root   4096 Nov 24 12:41 .
drwxrwxrwx 3 root root   4096 Nov 24 12:00 ..
-rw-r--r-- 1 root root  10240 Nov 24 12:00 permissions.sqlite3
-rw-r--r-- 1 root root 197120 Nov 24 12:00 test1.qcow2
-rw-r--r-- 1 root root 197120 Nov 24 12:41 test2.qcow2

Here is a tail of the log when I am creating the drive,

DEBUG   ::2014-11-24 12:40:43::utils.py:66::TNArchipelHypervisor.parse_own_repo (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::TNHypervisorRepoManager: begin to refresh own vmcast feed
DEBUG   ::2014-11-24 12:40:43::utils.py:66::TNArchipelHypervisor.parse_own_repo (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::TNHypervisorRepoManager: finish to refresh own vmcast feed
INFO    ::2014-11-24 12:40:52::utils.py:68::TNArchipelHypervisor.check_acp (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:permissions, action: getown
INFO    ::2014-11-24 12:40:53::utils.py:68::TNArchipelHypervisor.check_acp (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:hypervisor:health, action: history
INFO    ::2014-11-24 12:40:53::utils.py:68::TNArchipelHypervisor.check_perm (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::Checking permission for action health_history asked by admin@viper.dantownend.co.uk/ArchipelController
DEBUG   ::2014-11-24 12:40:53::utils.py:66::TNArchipelHypervisor.iq_health_info_history (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::Converting stats into XML node.
DEBUG   ::2014-11-24 12:40:53::archipelStatsCollector.py:109::STATCOLLECTOR: Retrieving last 100 recorded stats data for sending.
INFO    ::2014-11-24 12:40:53::utils.py:68::TNArchipelHypervisor.check_acp (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:hypervisor:health, action: info
INFO    ::2014-11-24 12:40:53::utils.py:68::TNArchipelHypervisor.check_perm (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::Checking permission for action health_info asked by admin@viper.dantownend.co.uk/ArchipelController
DEBUG   ::2014-11-24 12:40:53::archipelStatsCollector.py:109::STATCOLLECTOR: Retrieving last 1 recorded stats data for sending.
INFO    ::2014-11-24 12:40:58::utils.py:68::TNArchipelHypervisor.check_acp (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:hypervisor:health, action: info
INFO    ::2014-11-24 12:40:58::utils.py:68::TNArchipelHypervisor.check_perm (viper@viper.dantownend.co.uk/viper.dantownend.co.uk)::Checking permission for action health_info asked by admin@viper.dantownend.co.uk/ArchipelController
DEBUG   ::2014-11-24 12:40:58::archipelStatsCollector.py:109::STATCOLLECTOR: Retrieving last 1 recorded stats data for sending.
INFO    ::2014-11-24 12:41:01::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:permissions, action: getown
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action info asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:vm:oom, action: getadjust
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action oom_getadjust asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:virtualmachine:vnc, action: display
INFO    ::2014-11-24 12:41:02::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action vnc_display asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:vm:disk, action: get
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action drives_get asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.iq_get (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Info about disks sent.
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:vm:disk, action: get
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action drives_get asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:04::utils.py:68::TNArchipelVirtualMachine.iq_get (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Info about disks sent.
INFO    ::2014-11-24 12:41:06::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: get, namespace: archipel:vm:disk, action: getgolden
INFO    ::2014-11-24 12:41:06::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action drives_getgolden asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:06::utils.py:68::TNArchipelVirtualMachine.iq_getgolden (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Info about golden sent.
INFO    ::2014-11-24 12:41:13::utils.py:68::TNArchipelVirtualMachine.check_acp (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::acp received: from: admin@viper.dantownend.co.uk/ArchipelController, type: set, namespace: archipel:vm:disk, action: create
INFO    ::2014-11-24 12:41:13::utils.py:68::TNArchipelVirtualMachine.check_perm (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::Checking permission for action drives_create asked by admin@viper.dantownend.co.uk/ArchipelController
INFO    ::2014-11-24 12:41:13::utils.py:68::TNArchipelVirtualMachine.iq_create (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::disk created
INFO    ::2014-11-24 12:41:13::utils.py:68::TNArchipelVirtualMachine.shout (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::SHOUTING : shouting message to admin@viper.dantownend.co.uk
INFO    ::2014-11-24 12:41:13::utils.py:68::TNArchipelVirtualMachine.push_change (77a9ac3e-73d1-11e4-84fb-90e2ba0cb951@viper.dantownend.co.uk/viper)::PUSH : pushing archipel:push:disk->created

**Comment by viulian** [comment]
I have the same error using the current GIT code.
I had to remove APScheduler 3.0.1 and install version 2.1.2 ...

pip uninstall APScheduler
pip install -Iv https://pypi.python.org/packages/source/A/APScheduler/APScheduler-2.1.2.tar.gz#md5=6862959d460c16ef325d63e1fc3a6684

Now I have got to the IMPORTANT NOTE step ...
