### ISSUE TITLE
Only "Chat" tab is available with hypervisor

### ISSUE THREAD

**Issue by spectrecode** [ArchipelProject/Archipel#1107]
For the life of me, I can't figure out what's wrong. 

In the user guide, I see this: "Select your hypervisor from your roster then select the tab named "Virtual Machines"" (followed by broken images).

The only tab that I can see is "Chat".

This happens on both my local hosted client and the deployed client at http://app.archipelproject.org/

![archipel](https://cloud.githubusercontent.com/assets/9044456/5604809/8ec41d1c-939a-11e4-8553-fa40c10e0f02.PNG)

**Comment by CyrilPeponnet** [comment]
Check log files from agent, you may have misconfigured something.
