### ISSUE TITLE
Unable to view or use modules

### ISSUE THREAD

**Issue by kanewinter** [ArchipelProject/Archipel#1109]
Not sure if this project is still active or not but I'd really like to use it to mange a few hundred KVM servers. Unfortunately I haven't been able to get it to work. I can connect hypervisors and even create a VM that is unuseable. I'm blocked by the inability to use ANY modules besides chat. See screenshot for clarification. I've been unable to find any info via Google partially because I'm not sure what to even search for. I've tried several browers and test machines all with the same result. Please HELP!!

![archipelcomplaint](https://cloud.githubusercontent.com/assets/3288847/5771585/43199d38-9d0e-11e4-8ae8-17a5f79696e6.png)

**Comment by CyrilPeponnet** [comment]
Pretty sure you misconfigured something. 

Ejabberd configuration
Archipel configuration

Did you follow the wiki?

I suggest you to give a try with puppet-archipel using vagrant. This setup works and you will be able to understand what is wrong with your. 

This project is still active at some point. No major evolution planned but major bug fixes are still done. Check the commit history, you'll see. 

I assure it's will work if you follow every steps of the wiki page.

**Comment by kanewinter** [comment]
I've been going of the documentation over and over the past two days. Any
ideas on where to look? I tried two different versions of the gui and your
hosted copy. I'm going to rebuild my XMPP server again and try using Fedora.

**Comment by CyrilPeponnet** [comment]
Use default configuration for wiki for ejabberd and default Archipel.conf.

**Comment by kanewinter** [comment]
I rebuild my XMPP. Fedora 21 and the Fedora ejabberd package. Worked
immediately!! Sorry for bothering you I was just very very frustrated. I
will have to retry this on Centos since that's what we use here. I have a
feeling the ejabberd package on EPEL for centos 6.5 has issues.

**Comment by CyrilPeponnet** [comment]
Works fine here with centos 6.5 and 7. 

Check puppet-archipel it's based on 6.5
