### ISSUE TITLE
Problem Process on "top"

### ISSUE THREAD

**Issue by syNip** [ArchipelProject/Archipel#1110]
Hi,

I got 4VMs with Archipel, i install it with CentOS6.5, She's working as well, but in the last 3 days, MYSQL and SSH shutdown for no reason.

I have to reinstall the two applications after 2 days they crashed one time again, then i'm gonna looking into different forums and website no answer.

My problem is : in top command in linux i got 5 processes who generate randomly with a combinaison of 10 letters. This process kill and regenerate all the 10sec. This problem was only on my VMs generate with Archipel.

**Comment by CyrilPeponnet** [comment]
Don't think this is related to Archipel. But you can post a log.

**Comment by CyrilPeponnet** [comment]
Oh it's vm... So not related to Archipel but check if oom is enabled or not. This could be a serious lead for process killing.

**Comment by syNip** [comment]
Yes its VM, the prevent OOM is OFF, i tried to make it ON the problem is the same. and i dont think 1 second its an Archipel problem.

I juste want to know if anyone got a same problem in a VM

**Comment by CyrilPeponnet** [comment]
Post your top output and /v/l/messages

**Comment by syNip** [comment]
First top : 
1509 postfix   20   0 81700 4512 3344 S  0.0  0.1   0:00.06 local              
 1660 root      20   0 98.1m 4440 3424 S  0.0  0.1   0:00.36 sshd               
 1507 postfix   20   0 81552 3940 2984 S  0.0  0.1   0:00.03 cleanup            
 1257 postfix   20   0 81476 3924 2968 S  0.0  0.1   0:00.04 qmgr               
 1256 postfix   20   0 81408 3832 2892 S  0.0  0.1   0:00.04 pickup             
 1246 root      20   0 81328 3800 2856 S  0.0  0.1   0:00.05 master             
 1725 postfix   20   0 81416 3800 2872 S  0.0  0.1   0:00.03 trivial-rewrite    
 1319 root      18  -2 12424 2596  524 S  0.0  0.1   0:00.00 udevd              
 1320 root      18  -2 12424 2596  524 S  0.0  0.1   0:00.00 udevd              
 1678 root      20   0  105m 1840 1472 S  0.0  0.0   0:00.06 bash               
 1113 root      20   0  249m 1616 1036 S  0.0  0.0   0:00.09 rsyslogd           
  403 root      16  -4 11376 1468  320 S  0.0  0.0   0:00.50 udevd              
    1 root      20   0 19232 1456 1188 S  0.3  0.0   0:00.87 init               
 1258 root      20   0  114m 1384  736 S  0.0  0.0   0:02.00 crond              
 1168 root      20   0 66688 1244  496 S  0.0  0.0   0:00.03 sshd               
 1689 root      20   0 15020 1236  952 R  0.3  0.0   0:00.12 top                
 1734 root      20   0  1456 1004  156 S  0.0  0.0   0:00.00 asslaivvkb        <- This process 
 1731 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 asslaivvkb         
 1738 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 asslaivvkb         
 1740 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 asslaivvkb         
 1735 root      20   0  1456  996  156 S  0.0  0.0   0:00.00 asslaivvkb         
 1093 root      16  -4 27596  784  552 S  0.0  0.0   0:00.00 auditd             
 1301 root      20   0  4064  572  488 S  0.0  0.0   0:00.02 mingetty           
 1303 root      20   0  4064  572  488 S  0.0  0.0   0:00.00 mingetty           
 1305 root      20   0  4064  572  488 S  0.0  0.0   0:00.00 mingetty           
 1309 root      20   0  4064  568  488 S  0.0  0.0   0:00.00 mingetty           
 1314 root      20   0  4064  568  488 S  0.0  0.0   0:00.00 mingetty           
 1307 root      20   0  4064  564  488 S  0.0  0.0   0:00.00 mingetty           
 1265 root      20   0 31636  548  212 S  5.9  0.0   0:05.44 ltuiqxhoye   

Second Top : 

1509 postfix   20   0 81700 4512 3344 S  0.0  0.1   0:00.06 local              
 1660 root      20   0 98.1m 4440 3424 S  0.0  0.1   0:00.37 sshd               
 1507 postfix   20   0 81552 3940 2984 S  0.0  0.1   0:00.03 cleanup            
 1257 postfix   20   0 81476 3924 2968 S  0.0  0.1   0:00.04 qmgr               
 1256 postfix   20   0 81408 3832 2892 S  0.0  0.1   0:00.04 pickup             
 1246 root      20   0 81328 3800 2856 S  0.0  0.1   0:00.05 master             
 1319 root      18  -2 12424 2596  524 S  0.0  0.1   0:00.00 udevd              
 1320 root      18  -2 12424 2596  524 S  0.0  0.1   0:00.00 udevd              
 1678 root      20   0  105m 1840 1472 S  0.0  0.0   0:00.06 bash               
 1113 root      20   0  249m 1616 1036 S  0.0  0.0   0:00.09 rsyslogd           
  403 root      16  -4 11376 1468  320 S  0.0  0.0   0:00.50 udevd              
    1 root      20   0 19232 1456 1188 S  0.0  0.0   0:00.88 init               
 1258 root      20   0  114m 1384  736 S  0.0  0.0   0:02.00 crond              
 1168 root      20   0 66688 1244  496 S  0.0  0.0   0:00.03 sshd               
 1689 root      20   0 15020 1240  952 R  0.3  0.0   0:00.17 top                
 1836 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 pxxjwddupb         <- Replace of process
 1839 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 pxxjwddupb          of the first top
 1843 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 pxxjwddupb         
 1845 root      20   0  1456 1000  156 S  0.0  0.0   0:00.00 pxxjwddupb         
 1842 root      20   0  1456  996  156 S  0.0  0.0   0:00.00 pxxjwddupb         
 1093 root      16  -4 27596  784  552 S  0.0  0.0   0:00.00 auditd             
 1301 root      20   0  4064  572  488 S  0.0  0.0   0:00.02 mingetty           
 1303 root      20   0  4064  572  488 S  0.0  0.0   0:00.00 mingetty           
 1305 root      20   0  4064  572  488 S  0.0  0.0   0:00.00 mingetty           
 1309 root      20   0  4064  568  488 S  0.0  0.0   0:00.00 mingetty           
 1314 root      20   0  4064  568  488 S  0.0  0.0   0:00.00 mingetty           
 1307 root      20   0  4064  564  488 S  0.0  0.0   0:00.00 mingetty           
 1265 root      20   0 31636  548  212 S  5.3  0.0   0:07.41 ltuiqxhoye

**Comment by syNip** [comment]
Jan 23 10:47:04 ES1 kernel: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
Jan 23 10:47:04 ES1 kernel: serio: i8042 KBD port at 0x60,0x64 irq 1
Jan 23 10:47:04 ES1 kernel: serio: i8042 AUX port at 0x60,0x64 irq 12
Jan 23 10:47:04 ES1 kernel: mice: PS/2 mouse device common for all mice
Jan 23 10:47:04 ES1 kernel: input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input2
Jan 23 10:47:04 ES1 kernel: rtc_cmos 00:01: RTC can wake from S4
Jan 23 10:47:04 ES1 kernel: rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
Jan 23 10:47:04 ES1 kernel: rtc0: alarms up to one day, 114 bytes nvram
Jan 23 10:47:04 ES1 kernel: cpuidle: using governor ladder
Jan 23 10:47:04 ES1 kernel: cpuidle: using governor menu
Jan 23 10:47:04 ES1 kernel: EFI Variables Facility v0.08 2004-May-17
Jan 23 10:47:04 ES1 kernel: usbcore: registered new interface driver hiddev
Jan 23 10:47:04 ES1 kernel: usbcore: registered new interface driver usbhid
Jan 23 10:47:04 ES1 kernel: usbhid: v2.6:USB HID core driver
Jan 23 10:47:04 ES1 kernel: GRE over IPv4 demultiplexor driver
Jan 23 10:47:04 ES1 kernel: TCP cubic registered
Jan 23 10:47:04 ES1 kernel: Initializing XFRM netlink socket
Jan 23 10:47:04 ES1 kernel: NET: Registered protocol family 17
Jan 23 10:47:04 ES1 kernel: registered taskstats version 1
Jan 23 10:47:04 ES1 kernel: rtc_cmos 00:01: setting system clock to 2015-01-23 09:46:51 UTC (1422006411)
Jan 23 10:47:04 ES1 kernel: Initalizing network drop monitor service
Jan 23 10:47:04 ES1 kernel: Freeing unused kernel memory: 1292k freed
Jan 23 10:47:04 ES1 kernel: Write protecting the kernel read-only data: 10240k
Jan 23 10:47:04 ES1 kernel: Freeing unused kernel memory: 788k freed
Jan 23 10:47:04 ES1 kernel: Freeing unused kernel memory: 1568k freed
Jan 23 10:47:04 ES1 kernel: dracut: dracut-004-356.el6
Jan 23 10:47:04 ES1 kernel: dracut: rd_NO_LUKS: removing cryptoluks activation
Jan 23 10:47:04 ES1 kernel: device-mapper: uevent: version 1.0.3
Jan 23 10:47:04 ES1 kernel: device-mapper: ioctl: 4.27.0-ioctl (2013-10-30) initialised: dm-devel@redhat.com
Jan 23 10:47:04 ES1 kernel: udev: starting version 147
Jan 23 10:47:04 ES1 kernel: dracut: Starting plymouth daemon
Jan 23 10:47:04 ES1 kernel: usb 1-1: new full speed USB device number 2 using uhci_hcd
Jan 23 10:47:04 ES1 kernel: dracut: rd_NO_MD: removing MD RAID activation
Jan 23 10:47:04 ES1 kernel: scsi0 : ata_piix
Jan 23 10:47:04 ES1 kernel: scsi1 : ata_piix
Jan 23 10:47:04 ES1 kernel: ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc000 irq 14
Jan 23 10:47:04 ES1 kernel: ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc008 irq 15
Jan 23 10:47:04 ES1 kernel: input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3
Jan 23 10:47:04 ES1 kernel: ata1.00: ATA-7: QEMU HARDDISK, 0.12.1, max UDMA/100
Jan 23 10:47:04 ES1 kernel: ata1.00: 167772160 sectors, multi 16: LBA48 
Jan 23 10:47:04 ES1 kernel: ata1.00: configured for MWDMA2
Jan 23 10:47:04 ES1 kernel: scsi 0:0:0:0: Direct-Access     ATA      QEMU HARDDISK    0.12 PQ: 0 ANSI: 5
Jan 23 10:47:04 ES1 kernel: ata2.00: ATAPI: QEMU DVD-ROM, 0.12.1, max UDMA/100
Jan 23 10:47:04 ES1 kernel: ata2.00: configured for MWDMA2
Jan 23 10:47:04 ES1 kernel: scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     0.12 PQ: 0 ANSI: 5
Jan 23 10:47:04 ES1 kernel: usb 1-1: New USB device found, idVendor=0627, idProduct=0001
Jan 23 10:47:04 ES1 kernel: usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=5
Jan 23 10:47:04 ES1 kernel: usb 1-1: Product: QEMU USB Tablet
Jan 23 10:47:04 ES1 kernel: usb 1-1: Manufacturer: QEMU 0.12.1
Jan 23 10:47:04 ES1 kernel: usb 1-1: SerialNumber: 42
Jan 23 10:47:04 ES1 kernel: usb 1-1: configuration #1 chosen from 1 choice
Jan 23 10:47:04 ES1 kernel: input: QEMU 0.12.1 QEMU USB Tablet as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/input/input4
Jan 23 10:47:04 ES1 kernel: generic-usb 0003:0627:0001.0001: input,hidraw0: USB HID v0.01 Pointer [QEMU 0.12.1 QEMU USB Tablet] on usb-0000:00:01.2-1/input0
Jan 23 10:47:04 ES1 kernel: Refined TSC clocksource calibration: 2194.709 MHz.
Jan 23 10:47:04 ES1 kernel: ACPI: PCI Interrupt Link [LNKA] enabled at IRQ 10
Jan 23 10:47:04 ES1 kernel: virtio-pci 0000:00:05.0: PCI INT A -> Link[LNKA] -> GSI 10 (level, high) -> IRQ 10
Jan 23 10:47:04 ES1 kernel: STARTING CRC_T10DIF
Jan 23 10:47:04 ES1 kernel: sd 0:0:0:0: [sda] 167772160 512-byte logical blocks: (85.8 GB/80.0 GiB)
Jan 23 10:47:04 ES1 kernel: sd 0:0:0:0: [sda] Write Protect is off
Jan 23 10:47:04 ES1 kernel: sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Jan 23 10:47:04 ES1 kernel: sda: sda1 sda2
Jan 23 10:47:04 ES1 kernel: sd 0:0:0:0: [sda] Attached SCSI disk
Jan 23 10:47:04 ES1 kernel: sr0: scsi3-mmc drive: 4x/4x xa/form2 tray
Jan 23 10:47:04 ES1 kernel: Uniform CD-ROM driver Revision: 3.20
Jan 23 10:47:04 ES1 kernel: dracut: Scanning devices sda2  for LVM logical volumes vg_es1/lv_root vg_es1/lv_swap 
Jan 23 10:47:04 ES1 kernel: dracut: inactive '/dev/vg_es1/lv_root' [50.00 GiB] inherit
Jan 23 10:47:04 ES1 kernel: dracut: inactive '/dev/vg_es1/lv_home' [24.65 GiB] inherit
Jan 23 10:47:04 ES1 kernel: dracut: inactive '/dev/vg_es1/lv_swap' [4.86 GiB] inherit
Jan 23 10:47:04 ES1 kernel: EXT4-fs (dm-0): INFO: recovery required on readonly filesystem
Jan 23 10:47:04 ES1 kernel: EXT4-fs (dm-0): write access will be enabled during recovery
Jan 23 10:47:04 ES1 kernel: EXT4-fs (dm-0): recovery complete
Jan 23 10:47:04 ES1 kernel: EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: 
Jan 23 10:47:04 ES1 kernel: dracut: Mounted root filesystem /dev/mapper/vg_es1-lv_root
Jan 23 10:47:04 ES1 kernel: dracut: Loading SELinux policy
Jan 23 10:47:04 ES1 kernel: type=1404 audit(1422006413.167:2): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
Jan 23 10:47:04 ES1 kernel: type=1403 audit(1422006413.963:3): policy loaded auid=4294967295 ses=4294967295
Jan 23 10:47:04 ES1 kernel: dracut: 
Jan 23 10:47:04 ES1 kernel: dracut: Switching root
Jan 23 10:47:04 ES1 kernel: udev: starting version 147
Jan 23 10:47:04 ES1 kernel: sd 0:0:0:0: Attached scsi generic sg0 type 0
Jan 23 10:47:04 ES1 kernel: sr 1:0:0:0: Attached scsi generic sg1 type 5
Jan 23 10:47:04 ES1 kernel: piix4_smbus 0000:00:01.3: SMBus Host Controller at 0xb100, revision 0
Jan 23 10:47:04 ES1 kernel: 8139cp: 10/100 PCI Ethernet driver v1.3 (Mar 22, 2004)
Jan 23 10:47:04 ES1 kernel: ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 11
Jan 23 10:47:04 ES1 kernel: 8139cp 0000:00:03.0: PCI INT A -> Link[LNKC] -> GSI 11 (level, high) -> IRQ 11
Jan 23 10:47:04 ES1 kernel: eth0: RTL-8139C+ at 0xffffc900020d8000, de:ad:5b:86:0c:5c, IRQ 11
Jan 23 10:47:04 ES1 kernel: 8139cp 0000:00:04.0: PCI INT A -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
Jan 23 10:47:04 ES1 kernel: eth1: RTL-8139C+ at 0xffffc9000172e000, de:ad:19:ad:dc:8a, IRQ 11
Jan 23 10:47:04 ES1 kernel: 8139too Fast Ethernet driver 0.9.28
Jan 23 10:47:04 ES1 kernel: EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: 
Jan 23 10:47:04 ES1 kernel: EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: 
Jan 23 10:47:04 ES1 kernel: Adding 5095420k swap on /dev/mapper/vg_es1-lv_swap.  Priority:-1 extents:1 across:5095420k 
Jan 23 10:47:04 ES1 kernel: NET: Registered protocol family 10
Jan 23 10:47:04 ES1 kernel: lo: Disabled Privacy Extensions
Jan 23 10:47:04 ES1 kernel: ip6_tables: (C) 2000-2006 Netfilter Core Team
Jan 23 10:47:04 ES1 kernel: nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
Jan 23 10:47:04 ES1 kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Jan 23 10:47:04 ES1 kernel: eth0: link up, 100Mbps, full-duplex, lpa 0x05E1
Jan 23 10:47:04 ES1 kernel: eth1: link up, 100Mbps, full-duplex, lpa 0x05E1
Jan 23 10:47:04 ES1 kernel: type=1305 audit(1422006424.495:4): audit_pid=1093 old=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:auditd_t:s0 res=1

**Comment by moobyfr** [comment]
your host is probably hacked , verify the integrity of your system.

**Comment by syNip** [comment]
Hi, Thanks for your answer moobyfr how can i do that easily ?

**Comment by moobyfr** [comment]
ask your sysadmin, your your SSI, a first search on random process on linux, in google speak about DDOS tools

**Comment by syNip** [comment]
OK, after many search i found in chkconfig --list a virus who only propagate in chkconfig.

I didn't locate the source but it's a virus.
I close the issue thanks for helping.
