### ISSUE TITLE
Client crash when adding a VM Guest

### ISSUE THREAD

**Issue by ruthger** [ArchipelProject/Archipel#1113]
When adding a new or existing VM Guest the client crashes.

2015-02-23 09:54:03.414 Cappuccino [error]: CPInvalidArgumentException: Range {-1, 1} is out of bounds.
Objective-J.js:427 CPLogConsole

**Comment by CyrilPeponnet** [comment]
Are you using the nightlies? Because I can't reproduce here and I use Archipel everyday.

**Comment by ruthger** [comment]
I'm using nighlty. I even have it when I use app.archipelproject.org.
I made an error in the description. It's only when I add an existing VM Guest to my roster. I have clear my cache twice and restarted chrome, to be sure. There is nothing found in the archipel-agent logs or ejabberd logs.

**Comment by moobyfr** [comment]
I confirm the issue. I reproduce it when I want to manage an already existing VM, with the "eye" icon in the list of VM from an hypervisor

**Comment by CyrilPeponnet** [comment]
I can reproduce too and in several places. The bug occurs mainly when the tableview contain one item and this selected item disappear (due to previous actions such as manage vm, unpark, park…).


I will investigate this one.

**Comment by CyrilPeponnet** [comment]
This is not clear how this issue happens. Can you provide a test case with 100% fail ?

**Comment by CyrilPeponnet** [comment]
If someone can reproduce this with puppet-archipel (https://github.com/ArchipelProject/puppet-archipel)... because I've seen this bug before but I can't reproduce it on my dev environment.

**Comment by CyrilPeponnet** [comment]
I may have found something, let me fix this.
