### ISSUE TITLE
Fix images on Architecture & Concepts page

### ISSUE THREAD

**Issue by sradhakrishna** [ArchipelProject/Archipel#1115]
Hi,

The dropbox links on https://github.com/ArchipelProject/Archipel/wiki/Architecture-%26-Concepts page don't seem to be working. Can you please fix this?

For someone who is going to start off with this, that'd be very important.

Thanks,
Radha.

**Comment by CyrilPeponnet** [comment]
We tried but unfortunately all the images stored in Dropbox are gone... @primalmotion may recreate them one day...

**Comment by CyrilPeponnet** [comment]
Unfortunately images are lost... we will need to recreate them from scratch... I close this one.

**Comment by CyrilPeponnet** [comment]
We found them !!! I will fix the wiki soon :)
