### ISSUE TITLE
My archipel console is very slow and hard to log in!

### ISSUE THREAD

**Issue by topstarnetwork** [ArchipelProject/Archipel#1119]
Hello,
My archipel console is very slow and hard to log in!This happened aspecially when we added some other vps to it,
it seems that the swap was the problem.
My system admin does not get to know too well archipel,
could someone help?
Here below is the message I received from my system admin:

Technical Support || Staff
Hi Heather,

We are unable to work upon your requests as the Archipel is not loading. In fact it is loading but we are unable to connect and login to it.

It's taking a lot of time to connect and even after that the connection is not making through.

Can you please check this up with the node management team?

If at all, we are able to connect to Archipel, then only we will be able to work upon your requests.

===============================================
All the Best,

Technical Support || Staff
Hello Heather,

RAM usage was not the problem in the server. Swap was usage was causing slowness. I have cleared out swap space in the server. Please let me know if you are still facing slowness in the VPS.
======
[root@main ~]# free -m
total used free shared buffers cached
Mem: 32107 31884 223 0 42 4533
-/+ buffers/cache: 27308 4799
Swap: 4095 0 4095
=======

**Comment by CyrilPeponnet** [comment]
Use latest from nightlies it fixes a bunch of memory leaks.

**Comment by topstarnetwork** [comment]
Would you have a tutoral for this which I can forward to my system admin please
And how can they loging to archipel as the archipel console is not accessible?
Thanks

**Comment by K1773R** [comment]
@topstarnetwork its described in the README/wiki

**Comment by topstarnetwork** [comment]
the Archipel panel was upgraded successfully. However, the memory issue still persists.
I am not able to log in to archipel pane
Even I tried the upgrade the panel is not loading properly.
I am getting errors at back end through logs. The sample error log is attached.

**Comment by topstarnetwork** [comment]
DEBUG: socket       stop  Plugging <archipelcore.xmpp.transports.TCPsocket instance at 0x38de8c0> out of <archipelcore.xmpp.client.Client instance at 0x38de830>.
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <archipelcore.xmpp.transports.TCPsocket instance at 0x2a06560> into <archipelcore.xmpp.client.Client instance at 0x2a064d0>
DEBUG: socket       warn  Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket       error Failed to connect to remote host ('main.trans-world.org', 5222): Connection refused (111)
Traceback (most recent call last):
  File "/home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 139, in connect
    self._sock.connect(sa)
  File "<string>", line 1, in connect
error: [Errno 111] Connection refused
DEBUG: socket       stop  Plugging <archipelcore.xmpp.transports.TCPsocket instance at 0x2a06560> out of <archipelcore.xmpp.client.Client instance at 0x2a064d0>.
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <archipelcore.xmpp.transports.TCPsocket instance at 0x38deb48> into <archipelcore.xmpp.client.Client instance at 0x38deab8>
DEBUG: socket       warn  Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket       error Failed to connect to remote host ('main.trans-world.org', 5222): Connection refused (111)
Traceback (most recent call last):
  File "/home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 139, in connect
    self._sock.connect(sa)
  File "<string>", line 1, in connect
error: [Errno 111] Connection refused
DEBUG: socket       stop  Plugging <archipelcore.xmpp.transports.TCPsocket instance at 0x38deb48> out of <archipelcore.xmpp.client.Client instance at 0x38deab8>.

**Comment by topstarnetwork** [comment]
I can't access archipel admin console, the connection keeps on without connecting me,
I tried the following but it still does not work, can someone help me please?

We tried to reconfigure ejabberd to also have BOSH with the following command but it still does not work

netstat -tuln | grep 5280
