### ISSUE TITLE
Imported 64bit-VMs don't boot: "this kernel requires an x86-64 cpu"

### ISSUE THREAD

**Issue by explanar** [ArchipelProject/Archipel#1120]
Imported VM's by copying /var/lib/archipel and /vm
hypervisor ubuntu 14.04 LTS  Linux 3.13.0-46-generic #77-Ubuntu SMP x86_64 x86_64 x86_64  
Virsh: GNU/LinuxQEMU 1.2.2 Hypervisor: QEMU 2.0.0
Libvirt 1.1002.2
VMX enabled
qcow2 image compressed

VM's boot into crash after grub-menu "this kernel requires an x86-64 cpu ..."

Could this be caused by a different hypervisor kernel version?

XML (edited arch from i686 to x86_64):
````
<domain type="qemu">
  <name>_</name>
  <uuid>4ba09ce2-929e-11e4-a8ba-000b0e0f00ed</uuid>
  <memory unit="KiB">2097152</memory>
  <currentMemory unit="KiB">2097152</currentMemory>
  <vcpu placement="static">4</vcpu>
  <os>
    <type machine="pc-0.12" arch="x86_64">hvm</type>
    <boot dev="cdrom"/>
    <bootmenu enable="no"/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>destroy</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk device="disk" type="file">
      <driver type="qcow2" name="qemu"/>
      <source file="/vm//drives/4ba09ce2-929e-11e4-a8ba-000b0e0f00ed/disk.qcow2"/>
      <target bus="virtio" dev="vda"/>
      <address slot="0x05" bus="0x00" domain="0x0000" type="pci" function="0x0"/>
    </disk>
    <disk device="cdrom" type="file">
      <driver type="raw" name="qemu"/>
      <source file="/vm//iso/boot-repair-disk-64bit.iso"/>
      <target bus="sata" dev="sdc"/>
      <readonly/>
      <address bus="0" controller="0" type="drive" target="0" unit="2"/>
    </disk>
    <controller index="0" model="pci-root" type="pci"/>
    <controller index="0" type="sata">
      <address slot="0x04" bus="0x00" domain="0x0000" type="pci" function="0x0"/>
    </controller>
    <controller index="0" type="usb">
      <address slot="0x01" bus="0x00" domain="0x0000" type="pci" function="0x2"/>
    </controller>
    <interface type="bridge">
      <mac address="de:ad:66:31:11:fb"/>
      <source bridge="cubenet"/>
      <bandwidth>
      </bandwidth>
      <model type="virtio"/>
      <address slot="0x03" bus="0x00" domain="0x0000" type="pci" function="0x0"/>
    </interface>
    <input bus="usb" type="tablet"/>
    <input bus="ps2" type="mouse"/>
    <input bus="ps2" type="keyboard"/>
    <graphics autoport="yes" keymap="de" type="vnc" port="-1"/>
    <video>
      <model type="cirrus" vram="9216" heads="1"/>
      <address slot="0x02" bus="0x00" domain="0x0000" type="pci" function="0x0"/>
    </video>
    <memballoon model="virtio">
      <address slot="0x06" bus="0x00" domain="0x0000" type="pci" function="0x0"/>
    </memballoon>
  </devices>
</domain>
````

**Comment by CyrilPeponnet** [comment]
Well this seems clearly not related to archipel. Did you manage to create  new VM on this hypervisor with the same architecture ? (64bits)

**Comment by explanar** [comment]
yes, both architectures were x86_64.
The source-hypervisor was based on an installation of Ubuntu 14.04 LTS Server with additional Desktop install, the second hypervisor was based on Xubuntu 14.04.

Today i have setup another second hypervisor based on LTS server (no Desktop), installed Archipel and then installed xubuntu-desktop.

Didn't import anything yet (will be done soon), but a first (empty) test VM already generated an XML with x86_64 emulator - this was i386 by default on the Xubuntu-based test - so it should work.

I will update after the imports

**Comment by explanar** [comment]
Finally now the imported VM's work.

I don't know why the default emulator is i386 (and x86_64 doesn't semm to work via XML) after installing Archipel upon an empty Xubuntu Desktop.

I finally solved it by Installing Ubuntu Server without Desktop, 
then installing archipel and after that the xubuntu-desktop environment.
Maybe the some qemu/kvm package-dependency-resolves are being influenced.
