### ISSUE TITLE
I can't access archipel admin console

### ISSUE THREAD

**Issue by topstarnetwork** [ArchipelProject/Archipel#1121]
I can't access archipel admin console, the connection keeps on without connecting me,
I tried the following but it still does not work, can someone help me please?

We tried to reconfigure ejabberd to also have BOSH with the following command but it still does not work

netstat -tuln | grep 5280

**Comment by CyrilPeponnet** [comment]
Follow the wiki, this is not an issue.

**Comment by topstarnetwork** [comment]
Can you please reply this support ticket????
This is urgent, I can't log to archipel admin frontend console so,
the SSH shell for the terminal is accessible but through the terminal we are not able to work on any vps. In order to work on archipel adpinistration, we need to have access to the Archipel.

In this case as we can not access the archipel admin frontend console how can we get into archipel anyway?

**Comment by CyrilPeponnet** [comment]
Follow the wiki.

**Comment by topstarnetwork** [comment]
I had hired a system admin and eventhough this he could not make it,
please give me the url wiki link you are talking about once for ever wich describes on how to access archipel without the frotnend and manage the main node,
it has been 2 weeks I am not abel to access archipel, thanks

**Comment by CyrilPeponnet** [comment]
Maybe you should consider to fire him so. 

Wiki is on the right of github page.

**Comment by topstarnetwork** [comment]
Here is the log crash detail atatched file my system admin is sending me,
If he fails again could youtake a look at my server?
Regards, Heather


User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
Exception: TypeError: Cannot read property 'valueForKey' of null
	
Version: 0.5.0-db50124 (Moon)

 TypeError: Cannot read property 'valueForKey' of null,    at $CPKeyedUnarchiver__decodeObjectForKey_ (eval at <anonymous> (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:5868:1), <anonymous>:138:35),    at objj_msgSend (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:6413:8),    at $CPCib__instantiateCibWithExternalNameTable_ (eval at <anonymous> (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:5868:1), <anonymous>:91:22),    at objj_msgSend (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:6413:8),    at $CPViewController__loadView (eval at <anonymous> (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:5868:1), <anonymous>:100:71),    at objj_msgSend (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:6411:8),    at $CPViewController__view (eval at <anonymous> (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:5868:1), <anonymous>:113:9),    at objj_msgSend (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:6411:8),    at $TNModuleController___manageTabItemLoad_ (eval at <anonymous> (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:5867:16), <anonymous>:420:18),    at objj_msgSend (http://204.45.31.146/Archipel/Frameworks/Objective-J/Objective-J.js:6413:8)

**Comment by topstarnetwork** [comment]
I am not sure what is the problem here. I need someone from Archipel development or support to take a look into the problem.

[root@main ~]# service ejabberd start
Starting ejabberd: [ OK ]
[root@main ~]# netstat -tuln | grep 52
tcp 0 0 0.0.0.0:5269 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:5280 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:5281 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:5222 0.0.0.0:* LISTEN
[root@main ~]#
