### ISSUE TITLE
Error showing after having upgraded archipel agent and client

### ISSUE THREAD

**Issue by topstarnetwork** [ArchipelProject/Archipel#1122]
the Archipel panel was upgraded successfully. However, the memory issue still persists.
I am not able to log in to archipel pane
Even I tried the upgrade the panel is not loading properly.
I am getting errors at back end through logs. The sample error log is here below;

DEBUG: socket stop Plugging out of .
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG:
DEBUG: Debug created for /home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py
DEBUG: flags defined: always,nodebuilder
DEBUG: socket start Plugging into
DEBUG: socket warn Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket error Failed to connect to remote host ('main.trans-world.org', 5222): Connection refused (111)
Traceback (most recent call last):
File "/home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 139, in connect
self._sock.connect(sa)
File "", line 1, in connect
error: [Errno 111] Connection refused
DEBUG: socket stop Plugging out of .
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG:
DEBUG: Debug created for /home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/client.py
DEBUG: flags defined: always,nodebuilder
DEBUG: socket start Plugging into
DEBUG: socket warn Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket error Failed to connect to remote host ('main.trans-world.org', 5222): Connection refused (111)
Traceback (most recent call last):
File "/home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 139, in connect
self._sock.connect(sa)
File "", line 1, in connect
error: [Errno 111] Connection refused
DEBUG: socket stop Plugging out of .

**Comment by CyrilPeponnet** [comment]
ejabberd not running ? Connections refused not an archipel issue.
