### ISSUE TITLE
TRNG|/dev/random virtion-rng

### ISSUE THREAD

**Issue by K1773R** [ArchipelProject/Archipel#1126]
Is it possible to include the virtio-rng[0] settings/module into archipel?
Having a TRNG on the Host should also benefit the Guests.

[0] http://wiki.qemu-project.org/Features-Done/VirtIORNG

**Comment by CyrilPeponnet** [comment]
This must be supported by Libvirt if you want to be able to add this device to your vm through the xml definition.

**Comment by K1773R** [comment]
according to [0] its already implemented in libvirt.
they also add an example, will try this later.

that would be another manual XML entry that i have to set everytime i change something.
it would be quite usefull, if archipel can save additional xml entry which would be merged after validating changes. should i open another issue for this?

[0] https://libvirt.org/formatdomain.html#elementsRng

**Comment by CyrilPeponnet** [comment]
Updating the libvirt model is a pain... Once you had something through the xml editor, don't use the UI to change definition on your vm.

But if you want to improve the libvirt model, you can give a try:

https://github.com/ArchipelProject/Archipel/tree/master/ArchipelClient/ModulesSources/VirtualMachineDefinition/Model

**Comment by K1773R** [comment]
agree...

virtio-rng works for me with the XML adjustments :)
