### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by RomanBogachev** [ArchipelProject/Archipel#1128]
CentOS 6.6

```xml
ERROR   ::2015-03-26 02:35:32::utils.py:72::TNArchipelHypervisor.loop (my_archipel_data)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2015-03-26 02:35:32::utils.py:72::TNArchipelHypervisor.loop (my_archipel_data)::TRACEBACK: ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.6/site-packages/archipel_core-0.6.0beta-py2.6.egg/archipelcore/archipelEntity.py", line 1255, in loop\n    self.xmppclient.Process(3)\n', '  File "/usr/lib/python2.6/site-packages/xmpppy-0.5.0rc1-py2.6.egg/xmpp/dispatcher.py", line 303, in dispatch\n    handler[\'func\'](session,stanza)\n', '  File "/usr/lib/python2.6/site-packages/archipel_agent_hypervisor_health-0.6.0beta-py2.6.egg/archipelagenthypervisorhealth/health.py", line 168, in process_iq\n    conn.send(reply)\n', '  File "/usr/lib/python2.6/site-packages/xmpppy-0.5.0rc1-py2.6.egg/xmpp/dispatcher.py", line 367, in send\n    self._owner_send(stanza)\n', '  File "/usr/lib/python2.6/site-packages/xmpppy-0.5.0rc1-py2.6.egg/xmpp/transports.py", line 195, in send\n    self._owner.disconnected()\n', '  File "/usr/lib/python2.6/site-packages/xmpppy-0.5.0rc1-py2.6.egg/xmpp/client.py", line 129, in disconnected\n    for i in self.disconnect_handlers: i()\n', '  File "/usr/lib/python2.6/site-packages/xmpppy-0.5.0rc1-py2.6.egg/xmpp/client.py", line 137, in DisconnectHandler\n    raise IOError(\'Disconnected from server.\')\n', 'IOError: Disconnected from server.\n']
```

First time started - thats ok. After restarting server i have this issue. What can be the problem?

**Comment by CyrilPeponnet** [comment]
Be sure you don't launch archipel twice. Is there a stack trace before the log you gave ?

**Comment by RomanBogachev** [comment]
Good day! 

After clean rebooted server, i run `/etc/init.d/archipel` or `runarchipel`

In top: 

![TOP view](http://i.bogachev.biz/uploads/big/1b31096ae10883c71b10b907e050b1f9.png)

In Archipel Client

![archi client](http://i.bogachev.biz/uploads/big/9de76aa1d134b7033e43eed1fdc535c0.png)
Full log
https://gist.githubusercontent.com/RomanBogachev/443d78958e80c1c7c7f6/raw/19c8cc50a6ef8f2105721545820f44b51ff29bed/gistfile1.txt

**Comment by CyrilPeponnet** [comment]
You have multiple instance of archipel running. Kill them all stop the service and start the service again. 

Then I see something wrong with your installation. It seems that apscheduler is not installed or you have installed the 3.x release. You must install the 2.x.

**Comment by RomanBogachev** [comment]
It's installed with easy_install

Now reinstall

```sh
[root@cloudserver1 tmp]# pip install APScheduler==2.0.3
Collecting APScheduler==2.0.3
  Downloading APScheduler-2.0.3.tar.gz
    /tmp/pip-build-62WTjv/APScheduler/setup.py:12: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      import apscheduler
Installing collected packages: APScheduler
  Running setup.py install for APScheduler
Successfully installed APScheduler-2.0.3
```

the problem persists

**Comment by CyrilPeponnet** [comment]
How did you install archipel ? Use the nightlies.

**Comment by RomanBogachev** [comment]
I installed from published package..
I'll try to install from nightlies later and i'll write here if problem doesn't solved.
Thank you and please don't close this issue.

**Comment by CyrilPeponnet** [comment]
You can close it published eggs are 2 years old and they are not working anymore. 

This will be updated soon with beta7.
