### ISSUE TITLE
Dialog for New virtual machine is in French

### ISSUE THREAD

**Issue by ruthger** [ArchipelProject/Archipel#1131]
Just a minor bug. As of the latest build the dialog for New virtual machine is in French, Nouvelle machine virtualle. Also when using the Edit Virtual machine informations the same dialog is show with the text Nouvelle machine virtualle (probably New virtual machine) This should state Edit and not New.
I didn't check the older versions of the Archipel Client.

Also I would like to give my appreciations for this great project. I know development is going a bit slow due to lake of time, but it's getting better and more stable every commit.

**Comment by CyrilPeponnet** [comment]
Thanks! We appreciate. Thanks also for the input I'll check this asap.
