### ISSUE TITLE
Couldn't find index page for 'archipel-agent-centraldb'

### ISSUE THREAD

**Issue by baggar11** [ArchipelProject/Archipel#1136]
After upgrading to Ubuntu 14.04 I noticed that I couldn't boot off of x86 boot sector ISO's. The fix seemed to be nightlies or git. I opted for git. I purged /usr/local/lib/python2.7/dist-packages/archipel* and removed all the *archipel* lines from the easy-install.pth file as suggested from documentation.

I then git clone Archipel, run pull.sh, run (buildCentralAgent -d) under the BuildAgent directory, then run (buildAgent -d). Below is what I'm getting. It looks like more of source issue than local dependency issue as far as I can tell.

-----------------------------

Installed /root/Archipel/ArchipelAgent/archipel-agent
Processing dependencies for archipel-agent==0.6.0beta
Searching for archipel-agent-centraldb>=0.6.0beta
Reading https://pypi.python.org/simple/archipel-agent-centraldb/
Couldn't find index page for 'archipel-agent-centraldb' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for archipel-agent-centraldb>=0.6.0beta
error: Could not find suitable distribution for Requirement.parse('archipel-agent-centraldb>=0.6.0beta')
ERROR: Unable to install EGG package archipel-agent in developer mode

**Comment by CyrilPeponnet** [comment]
Could be related to
https://github.com/ArchipelProject/Archipel/commit/69f5c6f050b244f07aae58c78733ae93f7e989e5

Try to put the `--no-deps` back and report.

**Comment by baggar11** [comment]
I know a bit of python, but I'm unsure of what the fix could be. Any hints on what to try?

**Comment by baggar11** [comment]
Yep, that did the trick. Successful install and archipel init after that. Thanks!

**Comment by baggar11** [comment]
Sorry, should I have closed this so soon? Will these changes make it into mainline?

**Comment by baggar11** [comment]
Nevermind, I'm an idiot. I just saw the commit. Thanks!
