### ISSUE TITLE
'ImportError: cannot import name xmpp'

### ISSUE THREAD

**Issue by deliciousfudge** [ArchipelProject/Archipel#1138]
Running the following command (from https://github.com/ArchipelProject/Archipel/wiki/Central-agent):

sudo archipel-centralagentnode --jid=admin@mydomain.com --password=12345 --create

Gives me:

Traceback (most recent call last):
  File "/usr/local/bin/archipel-centralagentnode", line 10, in <module>
    execfile(__file__)
  File "/etc/Archipel/ArchipelAgent/archipel-core/install/bin/archipel-centralagentnode", line 27, in <module>
    from archipelcore import xmpp
ImportError: cannot import name xmpp

**Comment by CyrilPeponnet** [comment]
How did you install archipel in the first place?

**Comment by deliciousfudge** [comment]
Thanks for the quick response! I ran the following:

```
cd /etc
sudo git clone https://github.com/ArchipelProject/Archipel.git
cd Archipel/ArchipelAgent
sudo ./buildAgent  --devinstall
```

**Comment by CyrilPeponnet** [comment]
You have to init tye submodules as well.

https://github.com/ArchipelProject/Archipel/wiki/Installation:-Agent#from-the-sources
