### ISSUE TITLE
Problem connecting to archipel UI

### ISSUE THREAD

**Issue by silenceti** [ArchipelProject/Archipel#1141]
HI,

I've installed ejabberd and archipel in centos 7, but when I try the login, i've the following error:

 WebSocket connection to 'ws://archipel.local.domain:5280/xmpp' failed: Error during WebSocket handshake: Unexpected response code: 404 
 
 What can I do?

[root@archipel bin]# ./ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 15.04 is running in that node

 Thanks.

**Comment by CyrilPeponnet** [comment]
Use the ejabberd yaml configuration file provided in the wiki.

**Comment by silenceti** [comment]
I've used...this is my ejabberd.yml:

http://pastebin.com/itju3d1T

**Comment by CyrilPeponnet** [comment]
Can you reach archipel.local.domain:5280/ from your browser?

**Comment by CyrilPeponnet** [comment]
And use the yaml as provided

**Comment by silenceti** [comment]
404 Not Found

I guess this is the problem?

**Comment by CyrilPeponnet** [comment]
Yep, make sure your fqdn xmpp server is reachable from the machine displaying the UI (in the browser).

**Comment by silenceti** [comment]
Well, the port is listenning: 
tcp        0      0 0.0.0.0:5280            0.0.0.0:*               LISTEN      2120/beam.smp

And i can get to the Archipel ... so I guess is reachable, right?

**Comment by silenceti** [comment]
if I go here: http://archipel.local.domain:5280/http-bind , I get:

 ejabberd mod_http_bind

An implementation of XMPP over BOSH (XEP-0206)

This web page is only informative. To use HTTP-Bind you need a Jabber/XMPP client that supports it.

**Comment by CyrilPeponnet** [comment]
Try with https://www.websocket.org/echo.html <https://www.websocket.org/echo.html>

If it can’t connect, you must have an issue with your ejabberd configuration.

I just tried works fine for me.

**Comment by silenceti** [comment]
This browser supports WebSocket.

hum...Going to check ejabberd config

**Comment by CyrilPeponnet** [comment]
Did you do the test ?




You should get connected.

**Comment by CyrilPeponnet** [comment]
Did you do the test ?


![screen shot 2015-06-22 at 9 00 29 am](https://cloud.githubusercontent.com/assets/2277387/8286229/3ae487f6-18bd-11e5-8782-e93e74e862a0.png)


You should get connected.

**Comment by silenceti** [comment]
Mixed Content: The page at 'https://www.websocket.org/echo.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://archipel.local.domain:5280/xmpp?encoding=text'. This request has been blocked; this endpoint must be available over WSS.

**Comment by silenceti** [comment]
ERROR: The ejabberd node 'ejabberd@localhost' is already running.

this is normal? Doesn't supposed to be ejabberd@local.domain ?

**Comment by silenceti** [comment]
i've copy the file from here: https://github.com/ArchipelProject/Archipel/wiki/Ejabberd:-Configuration and it seems to be working :)

thanks CyrilPeponnet  for your help!

**Comment by itguy51** [comment]
I hate to re-open this issue, but I have run into the same troubles with a websocket connection 404ing, however, I am using the configuration file provided by the setup instructions. I attempted a WebSocket echo test, and it was unable to connect. I am able to log into the WebUI of ejabberd.
