### ISSUE TITLE
incomplete Client UI

### ISSUE THREAD

**Issue by Rustypredator** [ArchipelProject/Archipel#1145]
The Archipel UI i have installed locally seems to be incomplete and misses some features that are shown in the Demo Video. (e.g the "new VM" button next to the Screen button)
Also i can not manage Xmpp Users with the Archipel UI.

Am i missing some software on my enjabberd Server?
( Enjabberd and the UI are running on the same server. )

**Comment by CyrilPeponnet** [comment]
New vm button has been removed for now as this feature was not working properly. This doesn't means that you can not add vm!

In order to manage users your hypervisor or central agent must be ejabberd administrator. 

Check the wiki for more information.

**Comment by Rustypredator** [comment]
Well, i am using the Administrator Account that has been created by default (admin@fqdn.bla) and i can create vms, but not manage users

**Comment by CyrilPeponnet** [comment]
This is not related. XMPP user management is done through hypervisor or central agent entity so they need to be administrator as well. UI send XMPP to Agent and Agent take care of XMPP Users requests.

**Comment by Rustypredator** [comment]
So i log in to the central agent (the one running the enjabberd Server) with the administrator account that has been created by enjabberd at the installation. i have not created any other users (exept the ones The agents themthelves create when you configure them) With what account am i supposed to manage users if not with the initially created account mentioned above?

Or am i getting anything wrong?
so as you said above the central agent and hypervisor agents need to have administrator rights too?
using this command i dont remember anymore? :D something like
 ```enjabberdctl register centralnode@fqdn -c ```
as said, i dont remember the command, and cant find the site in the archipel wiki right now.

**Comment by CyrilPeponnet** [comment]
Check the FAQ. All is in here.

**Comment by Rustypredator** [comment]
well, seems that i have forgot to install something or something has went wrong, i will make a complete reinstall of the central hypervisor later today...
