### ISSUE TITLE
Many warnings during "easy_install apscheduler sqlalchemy numpy"

### ISSUE THREAD

**Issue by Rustypredator** [ArchipelProject/Archipel#1146]
Look at the paste at pastebin, there were far too many warnings to paste it here...
Im wondering if this is normal or im missing any package... im not that familliar with python, so i dont really know if i need any packages besides "python python-setuptools python-dev python-imaging python-numpy python-libvirt"
As you can see, at the end it says numpy is installed, so im assuming the warnings arent that critical.
If they are though please tell me!

-> http://pastebin.com/jwm7CzkY

Any help appreciated.

**Comment by CyrilPeponnet** [comment]
As long as it's only warning you are fine.
