### ISSUE TITLE
bootstrap java issue

### ISSUE THREAD

**Issue by volga629** [ArchipelProject/Archipel#1149]
Hello Everyone,
Trying build client  and having some issue with Cappuccino. Any help thank you.
OS: Fedora 21 Server x86_64
Java: 
 java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

 ```
Installation information
   - build Cappuccino            : True
   - build GrowlCappuccino       : True
   - build VNCCappuccino         : True
   - build StropheCappuccino     : True
   - build TNKit                 : True
   - build LPKit                 : True
   - build Archipel Client       : True
   - apply Cappuccino            : True
   - export to                   : ~/

 * Do you confirm ? [y/n] : y
 * Building Cappuccino

*******************************************************************************
Error: Narwhal is not compatible with your version of OpenJDK: OpenJDK Runtime Environment (build 1.8.0_51-b16).
Please upgrade to OpenJDK >= 6b18 or switch to the Sun JVM. Then re-run bootstrap.sh.
Unable to bootstrap Cappuccino
```

**Comment by YATV** [comment]
cd Archipel/ArchipelClient/Libraries/Cappuccino
 nano  bootstrap.sh

find this:
    # make sure user is running the Sun JVM or OpenJDK >= 6b18
    java_version=$(java -version 2>&1)
    echo $java_version | grep OpenJDK > /dev/null
    if [ "$?" = "0" ]; then # OpenJDK: make sure >= 6b18
        openjdk_version=$(echo "$java_version" | grep "OpenJDK Runtime Environment")
        openjdk_version_key=$(echo $openjdk_version | egrep -o '[0-9]\-?b[0-9]+')
        if [ $(echo $openjdk_version_key | tr -d 'b' | tr -d '-') -lt 618 ]; then
            echo "Error: Narwhal is not compatible with your version of OpenJDK: $openjdk_version."
            echo "Please upgrade to OpenJDK >= 6b18 or switch to the Sun JVM. Then re-run bootstrap.sh."
            exit 1
        fi
    fi

and comment line "exit 1"

    # make sure user is running the Sun JVM or OpenJDK >= 6b18
    java_version=$(java -version 2>&1)
    echo $java_version | grep OpenJDK > /dev/null
    if [ "$?" = "0" ]; then # OpenJDK: make sure >= 6b18
        openjdk_version=$(echo "$java_version" | grep "OpenJDK Runtime Environment")
        openjdk_version_key=$(echo $openjdk_version | egrep -o '[0-9]\-?b[0-9]+')
        if [ $(echo $openjdk_version_key | tr -d 'b' | tr -d '-') -lt 618 ]; then
            echo "Error: Narwhal is not compatible with your version of OpenJDK: $openjdk_version."
            echo "Please upgrade to OpenJDK >= 6b18 or switch to the Sun JVM. Then re-run bootstrap.sh."
            #exit 1
        fi
    fi

And tries again!

**Comment by volga629** [comment]
the resolved the issue, thanks
