### ISSUE TITLE
VNCCappuccino build

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1150]
# cd Archipel/ArchipelClient
    # ./bootstrap
    
    ...
    
    * VNCCappuccino build
    * Building StropheCappuccino
    (in /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino)
    (in /usr/Archipel/ArchipelClient/Libraries/StropheCappuccino)
    make strophe.js
    make[1]: Entering directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
    make stamp-bower
    make[2]: Entering directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
    npm install
    make[2]: npm: Command not found
    make[2]: *** [stamp-npm] Error 127
    make[2]: Leaving directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
    make[1]: *** [strophe.js] Error 2
    make[1]: Leaving directory `/usr/Archipel/ArchipelClient/Libraries/StropheCappuccino/strophejs'
    make: *** [strophe.min.js] Error 2
    Unable to build StropheCappuccino

OS: CentOS 7.1

**Comment by CyrilPeponnet** [comment]
Install npm ?
