### ISSUE TITLE
Exception: PUBSUB: can't add item. Node /archipel/centralagentkeepalive doesn't exists.

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1151]
INFO    ::2015-08-17 20:21:47.290::utils.py:72::TNArchipelCentralAgent.connect_xmpp (centralagent@mydomain/1-srv-h.mydomain)::Successfully connected to XMPP with JID centralagent@mydomain/1-srv-h.mydomain
INFO    ::2015-08-17 20:21:47.293::utils.py:72::TNArchipelCentralAgent.perform_hooks (centralagent@mydomain/1-srv-h.mydomain)::HOOK: going to run methods for hook HOOK_ARCHIPELENTITY_XMPP_CONNECTED
INFO    ::2015-08-17 20:21:47.296::utils.py:72::TNArchipelCentralAgent.auth_xmpp (centralagent@mydomain/1-srv-h.mydomain)::Trying to authentify the client with username centralagent and resource 1-srv-h.mydomain
INFO    ::2015-08-17 20:21:47.317::utils.py:72::TNArchipelCentralAgent.auth_xmpp (centralagent@mydomain/1-srv-h.mydomain)::Successfully authenticated.
INFO    ::2015-08-17 20:21:47.321::utils.py:72::TNArchipelCentralAgent.register_handlers (centralagent@mydomain/1-srv-h.mydomain)::PLUGIN: registering stanza handler for plugin xmppserver
INFO    ::2015-08-17 20:21:47.324::utils.py:72::TNArchipelCentralAgent.register_handlers (centralagent@mydomain/1-srv-h.mydomain)::PLUGIN: registering stanza handler for plugin platformrequest
INFO    ::2015-08-17 20:21:47.330::utils.py:72::TNArchipelCentralAgent.register_handlers (centralagent@mydomain/1-srv-h.mydomain)::PLUGIN: registering stanza handler for plugin centraldb
INFO    ::2015-08-17 20:21:47.333::utils.py:72::TNArchipelCentralAgent.register_handlers (centralagent@mydomain/1-srv-h.mydomain)::handlers registred
INFO    ::2015-08-17 20:21:47.341::utils.py:72::TNArchipelCentralAgent.perform_hooks (centralagent@mydomain/1-srv-h.mydomain)::HOOK: going to run methods for hook HOOK_ARCHIPELENTITY_XMPP_AUTHENTICATED
INFO    ::2015-08-17 20:21:47.414::utils.py:72::TNArchipelCentralAgent.change_presence (centralagent@mydomain/1-srv-h.mydomain)::status change: Online show:away
INFO    ::2015-08-17 20:21:47.447::utils.py:72::TNArchipelCentralAgent.hook_xmpp_authenticated (centralagent@mydomain/1-srv-h.mydomain)::CENTRALAGENT: entity centralagent@mydomain/1-srv-h.mydomain is now subscribed to events from node /archipel/centralagentkeepalive
INFO    ::2015-08-17 20:21:47.450::utils.py:72::TNArchipelCentralAgent.change_presence (centralagent@mydomain/1-srv-h.mydomain)::status change: Standby show:away
INFO    ::2015-08-17 20:21:47.459::utils.py:72::TNArchipelCentralAgent.manage_vcard (centralagent@mydomain/1-srv-h.mydomain)::VCARD: Asking for own vCard.
INFO    ::2015-08-17 20:21:47.478::utils.py:72::TNArchipelCentralAgent.did_receive_vcard (centralagent@mydomain/1-srv-h.mydomain)::VCARD: I already have a vCard.
INFO    ::2015-08-17 20:21:59.494::utils.py:72::TNArchipelCentralAgent.on_xmpp_loop_tick (centralagent@mydomain/1-srv-h.mydomain)::CENTRALAGENT: has not detected any central agent for the last 11.6442445032 seconds, becoming central agent.
ERROR   ::2015-08-17 20:21:59.497::utils.py:76::TNArchipelCentralAgent.loop (centralagent@mydomain/1-srv-h.mydomain)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2015-08-17 20:21:59.500::utils.py:76::TNArchipelCentralAgent.loop (centralagent@mydomain/1-srv-h.mydomain)::TRACEBACK: Traceback (most recent call last):

  File "/root/ArchipelAgent/archipel-core/archipelcore/archipelEntity.py", line 1249, in loop
    self.on_xmpp_loop_tick()

  File "/root/ArchipelAgent/archipel-central-agent/archipelcentral/archipelCentralAgent.py", line 791, in on_xmpp_loop_tick
    self.become_central_agent()

  File "/root/ArchipelAgent/archipel-central-agent/archipelcentral/archipelCentralAgent.py", line 260, in become_central_agent
    self.central_keepalive_pubsub.add_item(initial_keepalive)

  File "/root/ArchipelAgent/archipel-core/archipelcore/pubsub.py", line 263, in add_item
    raise Exception("PUBSUB: can't add item. Node %s doesn't exists." % self.nodename)

Exception: PUBSUB: can't add item. Node /archipel/centralagentkeepalive doesn't exists.

**Comment by CyrilPeponnet** [comment]
Come on please read the doc. 

https://github.com/ArchipelProject/Archipel/wiki/Central-agent

**Comment by YATV** [comment]
archipel-centralagentnode --jid=admin@mydomain --password=******** --create
SUCCESS: pubsub node /archipel/centralagentkeepalive created
 
Problem fixed.
Thanks
