### ISSUE TITLE
More errors after load start page.

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1164]
Clear install in new server.
After load start page, I found more error in nginx error logfile:

2015/10/30 15:16:26 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Frameworks/LPKit/Resources/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Frameworks/LPKit/Resources/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:26 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Frameworks/StropheCappuccino/Resources/Strophe/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Frameworks/StropheCappuccino/Resources/Strophe/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:28 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/csp-report" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "POST /csp-report HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:29 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Modules/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Modules/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:42 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Frameworks/VNCCappuccino/Resources/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Frameworks/VNCCappuccino/Resources/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:42 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Frameworks/VNCCappuccino/Resources/novnc/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Frameworks/VNCCappuccino/Resources/novnc/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:42 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/Frameworks/VNCCappuccino/Resources/spice/Info.plist" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "GET /Frameworks/VNCCappuccino/Resources/spice/Info.plist HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:43 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/csp-report" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "POST /csp-report HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:43 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/csp-report" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "POST /csp-report HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

**Comment by CyrilPeponnet** [comment]
You can ignore those errors.

**Comment by YATV** [comment]
From http://nightlies.archipelproject.org/
And other installations from sources.
The result is the same.

This:
2015/10/30 15:16:43 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/csp-report" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "POST /csp-report HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

2015/10/30 15:16:43 [error] 8582#0: *13 open() "/usr/ArchipelClient/Archipel/csp-report" failed (2: No such file or directory), client: 10.0.6.80, server: mydomain, request: "POST /csp-report HTTP/1.1", host: "mydomain", referrer: "https://mydomain/"

resolve:
  # touch /usr/ArchipelClient/Archipel/csp-report
