### ISSUE TITLE
Error: failed to make

### ISSUE THREAD

**Issue by YATV** [ArchipelProject/Archipel#1173]
* Building ArchipelClient
# begining build #e15a309
# moving to .
# jaking...
(in /usr/Archipel/ArchipelClient)
(in /usr/Archipel/ArchipelClient)
(in /usr/Archipel/ArchipelClient)
Error: failed to make directories leading to Build/Release/Archipel/Resources
# Error in build : 256
error during build
 * ArchipelClient built
 * Exporting archipel to /home/YaTv/ArchipelClient/
cp: cannot stat ‘./Build/Release/Archipel’: No such file or directory
 * Archipel Client exported

 Installation is now complete.

 * Continue ? [y/n] : y

[YaTv@kvm01 ArchipelClient]$ ll /home/YaTv/ArchipelClient/
total 0
[YaTv@kvm01 ArchipelClient]$ ll ./Build/Release/Archipel
ls: cannot access ./Build/Release/Archipel: No such file or directory
[YaTv@kvm01 ArchipelClient]$ pwd
/usr/Archipel/ArchipelClient

**Comment by primalmotion** [comment]
The build is working fine. If you have some issues, please kindly ask on the mailing list with some 'hello','could you' and other 'thanks' instead of polluting the tracker with logs we all know as we wrote them.
