### ISSUE TITLE
Ceph RBD

### ISSUE THREAD

**Issue by bdallen** [ArchipelProject/Archipel#1177]
I noticed you have the option for GlusterFS in the GUI for a network URI, any chance this could also implement a Ceph URI to connect the disc to a Ceph RBD. This would be an awesome feature.

As Per - http://docs.ceph.com/docs/hammer/rbd/libvirt/

**Comment by CyrilPeponnet** [comment]
this should already works if you set as following:

`rdb://host:port/libvirt-pool/new-libvirt-image`

As raw disk type Network.

The creation of image is not handle (yet) by Archipel.
