### ISSUE TITLE
Segmentation fault on raspberry pi armv6

### ISSUE THREAD

**Issue by zarere** [ArchipelProject/Archipel#1178]
Hi all,

I'm trying to run the latest version 16.2 but when i start the server with ejabberdctl foreground i got this:

    ejabberdctl foreground
    10:09:41.564 [info] Application lager started on node ejabberd@localhost
    10:09:41.834 [info] Application crypto started on node ejabberd@localhost
    10:09:42.055 [info] Application sasl started on node ejabberd@localhost
    10:09:42.457 [info] Application asn1 started on node ejabberd@localhost
    10:09:42.467 [info] Application public_key started on node ejabberd@localhost
    10:09:42.780 [info] Application ssl started on node ejabberd@localhost
    10:09:42.878 [info] Application fast_yaml started on node ejabberd@localhost
    10:09:43.028 [info] Application fast_tls started on node ejabberd@localhost
    10:09:43.212 [info] Application fast_xml started on node ejabberd@localhost
    10:09:43.326 [info] Application stringprep started on node ejabberd@localhost
    10:09:43.518 [info] Application ezlib started on node ejabberd@localhost
    10:09:43.720 [info] Application cache_tab started on node ejabberd@localhost
    10:09:47.201 [info] Application mnesia started on node ejabberd@localhost
    10:10:05.080 [info] Application inets started on node ejabberd@localhost
    /sbin/ejabberdctl: line 259:  2939 Segmentation fault      $EXEC_CMD "$CMD"

My hardware is 
raspberry pi with 512ram
root@raspberry:~# lscpu 
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1

I installed ejabberd from source.Please advise

**Comment by primalmotion** [comment]
This should be reported to @processone
https://github.com/processone/ejabberd
