### ISSUE TITLE
Cannot find central agent to request

### ISSUE THREAD

**Issue by Alecyrus** [ArchipelProject/Archipel#1179]
log:
WARNING ::2016-04-06 11:41:03.871::utils.py:75::TNArchipelHypervisor.proxify_user_iq (hitnslab.org@hitnslab.org/hitnslab.org)::XMPPSERVER: Unable to find central agent instance to pass requests.
ERROR   ::2016-04-06 11:41:03.873::utils.py:170::<archipelagentxmppserver.xmppserver.TNXMPPServerController instance at 0x7f02ca911710>.proxify_user_iq: exception raised is: 'Cannot find central agent to request.' triggered by stanza :
<iq xmlns="jabber:client" to="hitnslab.org@hitnslab.org/hitnslab.org" from="admin@hitnslab.org/ArchipelController" id="510" type="get"><query xmlns="archipel:xmppserver:users"><archipel action="number" humans_only="true" /></query></iq>

**Comment by CyrilPeponnet** [comment]
Did you install the central agent ? If not do so.

**Comment by CyrilPeponnet** [comment]
Xmpp management as well as get user list for permissions require the central agent. It will avoid to let your hypervisor be an ejabberd admin.

**Comment by CyrilPeponnet** [comment]
The wiki is not yet up to date.

**Comment by Alecyrus** [comment]
my steps are as follows:
# git clone https://github.com/ArchipelProject/Archipel.git
# cd Archipel
# ./pull.sh
# easy_install apscheduler sqlalchemy numpy
# cd ArchipelAgent
# ./buildAgent -d
# archipel-initinstall 

then edit the archipel.conf, and add these contents in the tail 
-------------------------------------------------------------------
[MODULES]

action_scheduler            = True
centraldb                   = True
geolocalization             = True
hypervisor_health           = True
hypervisor_network          = True
hypervisor_vmcasts          = True
iphone_notification         = False
oomkiller                   = True
snapshoting                 = True
storage                     = True
virtualmachine_appliance    = True
vnc                         = True
xmppserver                  = True
vmparking                   = True  # needs centraldb to be     activated

[CENTRALAGENT]
# centralagent can be :
#  - auto (default) : will be central agent if there is none already started
#  - force : will be central agent (be careful to configure only one of your hypervisors this way)
centralagent               = auto

[VNC]
vnc_certificate_file                        = None
vnc_only_ssl                                = False
vnc_enable_websocket_debug                  = True

----------------------------------------------------------------

and then  the error occurs,  and I run ./buildCentralAgent -d ,but it doesn't work.

**Comment by Alecyrus** [comment]
my steps are as follows:

git clone https://github.com/ArchipelProject/Archipel.git

cd Archipel

./pull.sh

easy_install apscheduler sqlalchemy numpy

cd ArchipelAgent

./buildAgent -d

archipel-initinstall

then edit the archipel.conf, and add these contents in the tail

[MODULES]

action_scheduler = True
centraldb = True
geolocalization = True
hypervisor_health = True
hypervisor_network = True
hypervisor_vmcasts = True
iphone_notification = False
oomkiller = True
snapshoting = True
storage = True
virtualmachine_appliance = True
vnc = True
xmppserver = True
vmparking = True # needs centraldb to be activated

[CENTRALAGENT]

centralagent can be :

- auto (default) : will be central agent if there is none already started

- force : will be central agent (be careful to configure only one of your hypervisors this way)

centralagent = auto

[VNC]
vnc_certificate_file = None
vnc_only_ssl = False
vnc_enable_websocket_debug = True

and then the error occurs, and I run ./buildCentralAgent -d ,but it doesn't work.

**Comment by Alecyrus** [comment]
my steps are as follows:

git clone https://github.com/ArchipelProject/Archipel.git

cd Archipel

./pull.sh

easy_install apscheduler sqlalchemy numpy

cd ArchipelAgent

./buildAgent -d

archipel-initinstall

then edit the archipel.conf, and add these contents in the tail

[MODULES]

action_scheduler = True
centraldb = True
geolocalization = True
hypervisor_health = True
hypervisor_network = True
hypervisor_vmcasts = True
iphone_notification = False
oomkiller = True
snapshoting = True
storage = True
virtualmachine_appliance = True
vnc = True
xmppserver = True
vmparking = True # needs centraldb to be activated

[CENTRALAGENT]

centralagent can be :

- auto (default) : will be central agent if there is none already started

- force : will be central agent (be careful to configure only one of your hypervisors this way)

centralagent = auto

[VNC]
vnc_certificate_file = None
vnc_only_ssl = False
vnc_enable_websocket_debug = True

and then the error occurs, and I run ./buildCentralAgent -d ,but it doesn't work.

**Comment by Alecyrus** [comment]
@CyrilPeponnet thanks for your reply.

My steps are as follows:
# git clone https://github.com/ArchipelProject/Archipel.git
# cd Archipel
# ./pull.sh
# easy_install apscheduler sqlalchemy numpy
# cd ArchipelAgent
# ./buildAgent -d
# archipel-initinstall

# archipel-tagnode -j admin@alecyrus.org -p  YourPassWD --create
# archipel-rolesnode -j admin@alecyrus.org -p YourPassWD --create
# archipel-adminaccounts -j admin@alecyrus.org -p YourPassWD --create

then add these contents in the tail:
------------------------------
[MODULES]

action_scheduler            = True
centraldb                   = True
geolocalization             = True
hypervisor_health           = True
hypervisor_network          = True
hypervisor_vmcasts          = True
iphone_notification         = False
oomkiller                   = True
snapshoting                 = True
storage                     = True
virtualmachine_appliance    = True
vnc                         = True
xmppserver                  = True
vmparking                   = True  # needs centraldb to be     activated

[CENTRALAGENT]
# centralagent can be :
#  - auto (default) : will be central agent if there is none already started
#  - force : will be central agent (be careful to configure only one of your hypervisors this way)
centralagent               = auto

[VNC]
vnc_certificate_file                        = None
vnc_only_ssl                                = False
vnc_enable_websocket_debug                  = True
-----------------------------

then the error occured, and I run thr  ./buildCentralAgent -d ,but it doesn't work...

**Comment by Alecyrus** [comment]
@CyrilPeponnet thanks for your reply.

My steps are as follows:
# git clone https://github.com/ArchipelProject/Archipel.git
# cd Archipel
# ./pull.sh
# easy_install apscheduler sqlalchemy numpy
# cd ArchipelAgent
# ./buildAgent -d
# archipel-initinstall

# archipel-tagnode -j admin@alecyrus.org -p  YourPassWD --create
# archipel-rolesnode -j admin@alecyrus.org -p YourPassWD --create
# archipel-adminaccounts -j admin@alecyrus.org -p YourPassWD --create

then add these contents in the tail:
------------------------------
[MODULES]

action_scheduler            = True
centraldb                   = True
geolocalization             = True
hypervisor_health           = True
hypervisor_network          = True
hypervisor_vmcasts          = True
iphone_notification         = False
oomkiller                   = True
snapshoting                 = True
storage                     = True
virtualmachine_appliance    = True
vnc                         = True
xmppserver                  = True
vmparking                   = True  # needs centraldb to be     activated

[CENTRALAGENT]
# centralagent can be :
#  - auto (default) : will be central agent if there is none already started
#  - force : will be central agent (be careful to configure only one of your hypervisors this way)
centralagent               = auto

[VNC]
vnc_certificate_file                        = None
vnc_only_ssl                                = False
vnc_enable_websocket_debug                  = True
-----------------------------

then the error occured, and I run thr  ./buildCentralAgent -d ,but it doesn't work...

**Comment by Alecyrus** [comment]
@CyrilPeponnet thanks for your reply.

My steps are as follows:

git clone https://github.com/ArchipelProject/Archipel.git
cd Archipel
./pull.sh
easy_install apscheduler sqlalchemy numpy
cd ArchipelAgent
./buildAgent -d
archipel-initinstall
archipel-tagnode -j admin@alecyrus.org -p  YourPassWD --create
archipel-rolesnode -j admin@alecyrus.org -p YourPassWD --create
archipel-adminaccounts -j admin@alecyrus.org -p YourPassWD --create

then add these contents in the tail:
------------------------------
[MODULES]

action_scheduler            = True
centraldb                   = True
geolocalization             = True
hypervisor_health           = True
hypervisor_network          = True
hypervisor_vmcasts          = True
iphone_notification         = False
oomkiller                   = True
snapshoting                 = True
storage                     = True
virtualmachine_appliance    = True
vnc                         = True
xmppserver                  = True
vmparking                   = True  # needs centraldb to be     activated

[CENTRALAGENT]

centralagent               = auto

[VNC]
vnc_certificate_file                        = None
vnc_only_ssl                                = False
vnc_enable_websocket_debug                  = True
-----------------------------

then the error occured, and I run thr  ./buildCentralAgent -d ,but it doesn't work...

**Comment by CyrilPeponnet** [comment]
Read the wiki, everything is explained.

**Comment by CyrilPeponnet** [comment]
https://github.com/ArchipelProject/Archipel/wiki/Installation-manual

**Comment by Alecyrus** [comment]
@CyrilPeponnet  one more question,,, about the command “./buildCentralAgent -d ” ，it takes long time when bulid the agent-core？

**Comment by CyrilPeponnet** [comment]
No it should build pretty quickly.

**Comment by Alecyrus** [comment]
@CyrilPeponnet  Thanks for your reply. 

look this..
----------------------------------
./buildCentralAgent -d

Adding archipel-agent-xmppserver 0.6.0beta to easy-install.pth file
Adding archipel-platformrequest-defaultcomputingunit 0.6.0beta to easy-install.pth file

Installed /home/hjk/Archipel/ArchipelAgent/archipel-central-agent-platformrequest

Installed /home/hjk/Archipel/ArchipelAgent/archipel-platformrequest-defaultcomputingunit

Installed /home/hjk/Archipel/ArchipelAgent/archipel-agent-xmppserver
Installing archipel-tagnode script to /usr/local/bin
Installing runcentralagent script to /usr/local/bin
Installing archipel-rolesnode script to /usr/local/bin
Installing archipel-adminaccounts script to /usr/local/bin
Installing archipel-centralagentnode script to /usr/local/bin
Installing archipel-central-agent-initinstall script to /usr/local/bin

Installed /home/hjk/Archipel/ArchipelAgent/archipel-central-agent
Installing archipel-testxmppserver script to /usr/local/bin
Installing archipel-ejabberdadmin script to /usr/local/bin

Installed /home/hjk/Archipel/ArchipelAgent/archipel-core
[]

----------------------------------

and the cursor just flashs at the end...    =_=!!!  I try it many times.... My os is ubuntu 14.04 server..

**Comment by Alecyrus** [comment]
@CyrilPeponnet  , the command “ ./buildAgent  ” is work,  what is the difference between “ ./buildAgent “ and "  and   “ ./buildCentralAgent  ” ?

**Comment by Alecyrus** [comment]
With the installation tutorial, I can not run “ # ./buildCentralAgent”, the command will always be stuck, but another command “ ./buildAgent ” don't. when I open  the GUI. the error occred:

![selection_012](https://cloud.githubusercontent.com/assets/13865581/14318453/7b046be2-fc3f-11e5-9b6e-6287601e5fb2.png)

 You said that the command " # ./buildCentralAgent " execution will be pretty quick, but I don't think so.  
Is it because of the network, or the python version?  I know my question is very stupid, but I still hope you can help me. 
It has taken me a long time.
