### ISSUE TITLE
Archipel-Core not found

### ISSUE THREAD

**Issue by marvin-bitterlich** [ArchipelProject/Archipel#1184]
Trying to install Archipel from source on a gentoo system. I got all dependencies i found on the wiki but when I run:
`> sudo python2 /usr/bin/archipel-initinstall`
`FATAL: you need to install archipel-core`

Installed the source version once, also tried:
`> sudo python2 -m easy_install archipel-core`
`Installed /usr/lib64/python2.7/site-packages/archipel_core-0.6.0b0.post0-py2.7.egg`

Any tips on how to install this from source?

**Comment by Kostronor** [comment]
Once I get this to install correctly from source, I will create an ebuild for the project. Maybe this will help other gentoo users build this software.

**Comment by ruthger** [comment]
I have made an PKGBUILD script for ArchLinux. Maybe you can use it by example.

https://aur.archlinux.org/packages/archipel-agent-git/
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=archipel-agent-git

**Comment by moobyfr** [comment]
don't use easy_install , it pull a very old version of Archipel IIRC
