### ISSUE TITLE
Provide script to automate installation

### ISSUE THREAD

**Issue by ikus060** [ArchipelProject/Archipel#1191]
I'm trying to install Archipel on a Debian Jessie server and it's really painful to go trough all the installation and configuration step required. 

To ease the pain, I recommend to provide an installation script (bash) to automate the installation of archipel with ejabberd server.

**Comment by CyrilPeponnet** [comment]
You can check puppet-archipel but it's centos centric.

**Comment by ikus060** [comment]
After all, the installation steps is simple once you get you hand on the right wiki page.

Closing this bug.
