### ISSUE TITLE
In archipel VMS are showing offline

### ISSUE THREAD

**Issue by moshaiky** [ArchipelProject/Archipel#1194]
In archipel interface im seeing VMs are offline. When i click any vm it says "entity is offline"

Following services started and running fine:

1. ejabberd
2. archipel

But in log im seeing below error, is related to this:

Traceback (most recent call last):
  File "/home/archipel/ArchipelAgent/archipel-core/archipelcore/xmpp/transports.py", line 139, in connect
    self._sock.connect(sa)
  File "<string>", line 1, in connect
error: [Errno 110] Connection timed out

**Comment by CyrilPeponnet** [comment]
Looks like a network connectivity issue. Check your firewalls and dns resolution for your ejabberd host.

**Comment by K1773R** [comment]
btw @CyrilPeponnet 
when a short disconnect happens, archipel wont reconnect to the jabber service and you'll have to restart it.

**Comment by moshaiky** [comment]
@CyrilPeponnet Thanks,

It was DNS issue which is fixed and worked fine. Now im able to see machine status as "Running".

But still we have one more issue that whenever i click on Play or Screen button to access VM a popup appear and it says Archipel crashed and it reload and again starts from Login page.

I saw below logs:

 

> .trans-world.org)::Screenshot sent
INFO    ::2016-10-24 12:48:28::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:28::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:33::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:33::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:34::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: screenshot
INFO    ::2016-10-24 12:48:34::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action screenshot asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:34::utils.py:72::TNArchipelVirtualMachine.iq_screenshot (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Screenshot sent
INFO    ::2016-10-24 12:48:39::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:39::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:44::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:44::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:44::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: screenshot
INFO    ::2016-10-24 12:48:44::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action screenshot asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:44::utils.py:72::TNArchipelVirtualMachine.iq_screenshot (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Screenshot sent
INFO    ::2016-10-24 12:48:49::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:49::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:55::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:48:55::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:55::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: screenshot
INFO    ::2016-10-24 12:48:55::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action screenshot asked by admin@main.trans-world.org/ArchipelController
INFO    ::2016-10-24 12:48:55::utils.py:72::TNArchipelVirtualMachine.iq_screenshot (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Screenshot sent
DEBUG   ::2016-10-24 12:48:58::utils.py:70::TNArchipelHypervisor.parse_own_repo (main.trans-world.org@main.trans-world.org/main.trans-world.org)::TNHypervisorRepoManager: begin to refresh own vmcast feed
DEBUG   ::2016-10-24 12:48:58::utils.py:70::TNArchipelHypervisor.parse_own_repo (main.trans-world.org@main.trans-world.org/main.trans-world.org)::TNHypervisorRepoManager: finish to refresh own vmcast feed
DEBUG   ::2016-10-24 12:48:58::utils.py:70::TNArchipelHypervisor.parse_own_repo (main.trans-world.org@main.trans-world.org/main.trans-world.org)::TNHypervisorRepoManager: begin to refresh own vmcast feed
DEBUG   ::2016-10-24 12:48:58::utils.py:70::TNArchipelHypervisor.parse_own_repo (main.trans-world.org@main.trans-world.org/main.trans-world.org)::TNHypervisorRepoManager: finish to refresh own vmcast feed
INFO    ::2016-10-24 12:49:00::utils.py:72::TNArchipelVirtualMachine.check_acp (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::acp received: from: admin@main.trans-world.org/ArchipelController, type: get, namespace: archipel:vm:control, action: info
INFO    ::2016-10-24 12:49:00::utils.py:72::TNArchipelVirtualMachine.check_perm (755914f6-517a-11e5-bd24-003048c588cc@main.trans-world.org/main.trans-world.org)::Checking permission for action info asked by admin@main.trans-world.org/ArchipelController
