### ISSUE TITLE
xmpp disconnect while getting archipel:hypervisor:health

### ISSUE THREAD

**Issue by nicolasochem** [ArchipelProject/Archipel#879]
On a fresh setup, xmpp disconnect are experienced when getting the initial health stats from the ui.
archipel agent log with debug enabled:
INFO    ::2013-08-29 12:53:52::utils.py:71::TNArchipelHypervisor.check_acp (sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com)::acp received: from: admin@mvdcrow01.us.alcatel-lucent.com/ArchipelController, type: get, namespace: archipel:hypervisor:health, action: history
INFO    ::2013-08-29 12:53:52::utils.py:71::TNArchipelHypervisor.check_perm (sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com)::Checking permission for action health_history asked by admin@mvdcrow01.us.alcatel-lucent.com/ArchipelController
DEBUG   ::2013-08-29 12:53:52::utils.py:69::TNArchipelHypervisor.iq_health_info_history (sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com)::Converting stats into XML node.
DEBUG   ::2013-08-29 12:53:52::archipelStatsCollector.py:109::STATCOLLECTOR: Retrieving last 100 recorded stats data for sending.
ERROR   ::2013-08-29 12:53:52::utils.py:75::TNArchipelHypervisor.loop (sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com)::LOOP EXCEPTION : Disconnected from server. Trying to reconnect in 5 seconds.
ERROR   ::2013-08-29 12:53:52::utils.py:75::TNArchipelHypervisor.loop (sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com)::TRACEBACK: Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/archipelcore/archipelEntity.py", line 1257, in loop
    self.xmppclient.Process(3)

  File "/usr/lib/python2.6/site-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)

  File "/usr/lib/python2.6/site-packages/archipelagenthypervisorhealth/health.py", line 168, in process_iq
    conn.send(reply)

  File "/usr/lib/python2.6/site-packages/xmpp/dispatcher.py", line 367, in send
    self._owner_send(stanza)

  File "/usr/lib/python2.6/site-packages/xmpp/transports.py", line 195, in send
    self._owner.disconnected()

  File "/usr/lib/python2.6/site-packages/xmpp/client.py", line 129, in disconnected
    for i in self.disconnect_handlers: i()

  File "/usr/lib/python2.6/site-packages/xmpp/client.py", line 137, in DisconnectHandler
    raise IOError('Disconnected from server.')

IOError: Disconnected from server.

Xmpppy debug :+1: DEBUG: socket       got   <iq from='admin@mvdcrow01.us.alcatel-lucent.com/ArchipelController' to='sim01.mvdcdev17.us.alcatel-lucent.com@mvdcrow01.us.alcatel-lucent.com/sim01.mvdcdev17.us.alcatel-lucent.com' type='get' id='75864'>
  <query xmlns='archipel:hypervisor:health'>
  <archipel action='history' limit='100'/>
  </query>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->get props->[u'archipel:hypervisor:health'] id->75864
DEBUG: socket       error Socket error while sending data
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/xmpp/transports.py", line 187, in send
    self._send(raw_data)
SSLError: [Errno 3] _ssl.c:1217: The operation did not complete (write)
DEBUG: client       stop  Disconnect detected
DEBUG: socket       error Socket operation failed
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/xmpp/transports.py", line 187, in send
    self._send(raw_data)
SSLError: [Errno 3] _ssl.c:1217: The operation did not complete (write)
Traceback (most recent call last):
  File "/usr/bin/runarchipel", line 175, in <module>
    main(config)
  File "/usr/bin/runarchipel", line 111, in main
    hypervisor.loop()
  File "/usr/lib/python2.6/site-packages/archipelcore/archipelEntity.py", line 1276, in loop
    time.sleep(5.0)
KeyboardInterrupt

Looks like ssl error.

**Comment by CyrilPeponnet** [comment]
fixed with latest
